### ISSUE TITLE
Merge with builds

### ISSUE THREAD

**Issue by nobody5050** [dahlia-os/releases#1]
Merge with dahlia-os/builds with new directory for iso releases

**Comment by nmcain** [comment]
yeah

**Comment by EnderNightLord-ChromeBook** [comment]
I agree that this is not needed.

**Comment by nmcain** [comment]
However builds is for all builds, and releases is for builds deemed
eligible for release

**Comment by nobody5050** [comment]
can we not setup tags for what release is viable for usage or not?

**Comment by nmcain** [comment]
if its a pre release its not viable
ᐧ

**Comment by nobody5050** [comment]
Closing, outdated.
