### ISSUE TITLE
Pangolin de doesn't launch

### ISSUE THREAD

**Issue by Frusadev** [dahlia-os/releases#13]
I've installed dahlia os legacy on my machine and launched it but unfortunatly it was only showing the os logo on the background.
When i did a right click, it shown me that it was openbox running

**Comment by Frusadev** [comment]
Intel pentium 4gb ram

**Comment by nmcain** [comment]
So, use the menu to open a terminal, then type `exec
/dahlia/pangolin_desktop/pangolin_desktop`
