### ISSUE TITLE
only wallpaper shows up and console shows flutter error in 200804

### ISSUE THREAD

**Issue by diabolic-preacher** [dahlia-os/releases#2]
tested the latest release (as of 17th august 2020) on a qemu virtual machine (using virt-manager gui). the os boots into desktop showing only wallpaper and tty1 showing the error as attached herein. 
![Screenshot_dahlia_2020-08-17_07:41:02](https://user-images.githubusercontent.com/67977107/90351513-13aeec80-e05e-11ea-90bc-f18c9e87b8b8.png)

**Comment by nmcain** [comment]
What wallpaper? dahliaOS Linux shows a fallback black and white dahliaOS logo, or (in 200804) a snow capped mountain.

**Comment by diabolic-preacher** [comment]
> What wallpaper? dahliaOS Linux shows a fallback black and white dahliaOS logo (if pangolin does not start), or (in 200804) a snow capped mountain if pangolin is able to start.

got the snow capped mountain but nothing else. i thought the console messages might help tell why

**Comment by larsb24** [comment]
@diabolic-preacher qemu doesn't scale dahlia properly, you might have to scroll down to see the taskbar

**Comment by diabolic-preacher** [comment]
> @diabolic-preacher qemu doesn't scale dahlia properly, you might have to scroll down to see the taskbar

thanks for pointing that out. it is a really nice ui and i hope more dev happens on it. closing the issue here.
