### ISSUE TITLE
Can't boot with qemu

### ISSUE THREAD

**Issue by fctorial** [dahlia-os/releases#3]
Got a message saying 'Boot failed: Could not read from CDROM' when booting latest efi release with qemu:

    qemu-system-x86_64 -boot d -cdrom dahlia.iso -m 512 -hda mydisk.img

```
$ qemu-system-x86_64 --version
QEMU emulator version 4.2.0
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

**Comment by nmcain** [comment]
Is this the EFI image or the legacy image?

**Comment by fctorial** [comment]
latest efi release

**Comment by HexaOneOfficial** [comment]
did you read the instructions? 
https://github.com/dahlia-os/documentation/blob/master/run%20DahliaOS/qemu.md

**Comment by nmcain** [comment]
Ah, those are designed for hardware, I was not quite sure how to get the
EFI images working as Hybrid ISO images, the legacy image is compatible
with qemu using the following command on Linux: `qemu-system-x86_64
--enable-kvm -m 4096 -cdrom output/images/rootfs.iso`

**Comment by fctorial** [comment]
Same results with -enable-kvm:

https://prnt.sc/vcflyv

**Comment by nmcain** [comment]
Make sure that the specified image is a legacy image, you won't need a storage partition for it, it is purely a live image.

**Comment by fctorial** [comment]
@nmcain legacy iso works
