### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by mawoka-myblock** [dahlia-os/releases#4]
Please add also a Checksum to the releases! It would be very nice

**Comment by mawoka-myblock** [comment]
You can close the issue, no problem but please think for it...

**Comment by nmcain** [comment]
> You can close the issue, no problem but please think for it...
Ah, no, that was an accident. I've put it in the project board, and it's slated for the next release tomorrow.

**Comment by mawoka-myblock** [comment]
Cool

**Comment by nmcain** [comment]
@mawoka-myblock, Sums are now with the latest release, thanks for the tip!
